"""entry table

Revision ID: f3972197d855
Revises: 
Create Date: 2021-11-03 14:43:58.274606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3972197d855'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('blood_level', sa.String(length=64), nullable=True),
    sa.Column('juice_level', sa.String(length=64), nullable=True),
    sa.Column('first_day', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_entry_date'), 'cycle_entry', ['date'], unique=False)
    op.create_index(op.f('ix_cycle_entry_first_day'), 'cycle_entry', ['first_day'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cycle_entry_first_day'), table_name='cycle_entry')
    op.drop_index(op.f('ix_cycle_entry_date'), table_name='cycle_entry')
    op.drop_table('cycle_entry')
    # ### end Alembic commands ###
